# Generated by Django 5.0.6 on 2024-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
